language: elixir

elixir:
  - 1.8.0

addons:
  postgresql: '10.9'

service:
  - postgresql

before script:
  - psql -c 'create database rankings_test;' -U postgres
  # - cp config/test.exs config/travis.exs

script:
  - mix deps.get --only test
  - mix ecto.create
  - mix ecto.migrate
  - mix test